siteshd/siteshd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sshdapp.urls', namespace='sshdapp'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

siteshd/sshdapp/urls.py
from django.urls import path
from sshdapp import views

app_name = 'sshdapp'

urlpatterns = [
    path('', views.main_view, name='index'),
    path('vvod/', views.vvod_view, name='vvod'),
    path('ftbl/<str:sez>/', views.TovostListView.as_view(), name='ftbl'),
    path('instrp/<str:uin>/', views.TovostDetail.as_view(), name='instrp'),
    path('spr_sez', views.SezListView.as_view(), name='spr_sez'),
    path('spr_razm', views.RazmListView.as_view(), name='spr_razm')

]

siteshd/sshdapp/models.py
from django.db import models

class Sezon(models.Model):

    name = models.CharField(max_length=20, unique=True)

    # Основные типы полей
    # дата
    # models.DateField
    # models.DateTimeField
    # models.TimeField
    # # Числа
    # models.IntegerField
    # models.PositiveIntegerField
    # models.PositiveSmallIntegerField
    # models.FloatField
    # models.DecimalField
    # # Логический
    # models.BooleanField
    # # Байты (blob)
    # models.BinaryField
    # # Картинка
    # models.ImageField
    # # Файл
    # models.FileField
    # # url, email
    # models.URLField
    # models.EmailField

    def __str__(self):
        return self.name


class Razm(models.Model):

    name = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name


class Tovost(models.Model):

    uin = models.CharField(max_length=40)
    name = models.CharField(max_length=100)
    descriptions = models.TextField()
    ostatok = models.DecimalField(max_digits=10, decimal_places=0)
    cena = models.DecimalField(max_digits=10, decimal_places=2)
    kartss = models.TextField()
    ship = models.BooleanField()
    # Связь с сезонностью один - много
    sezonnost = models.ForeignKey(Sezon, on_delete=models.CASCADE)
    razmer = models.ForeignKey(Razm, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

siteshd/sshdapp/forms.py
from django import forms
from .models import Sezon, Razm

class SezonForm(forms.ModelForm):
    name = forms.CharField(label='Название')
    class Meta:
        model = Sezon
        fields = '__all__'

class RazmerForm(forms.ModelForm):
    name = forms.CharField(label='Название')
    class Meta:
        model = Razm
        fields = '__all__'

siteshd/sshdapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.base import ContextMixin
from .models import Sezon, Razm, Tovost
from .forms import SezonForm

# Create your views here.
def main_view(request):
    pass
    return render(request, 'sshdapp/index.html', context={})

def vvod_view(request):
    pass
    return render(request, 'sshdapp/vvod.html', context={})

def ftbl_view(request):

    f_sez = request.POST.get("f_sez", "")
    f_razm = request.POST.get("f_razm", "")

    print(f_sez)
    print(f_razm)

    lstsh = {}

    if f_sez is None and f_razm is None:
        c_sez = Sezon.objects.filter(name=f_sez).first()
        c_razm = Razm.objects.filter(name=f_razm).first()

        print(f_sez, c_sez, f_razm, c_razm)

        lstsh = Tovost.objects.filter(razmer=c_razm, sezonnost=c_sez)
        for ish in lstsh:
            print(ish.name)

    else:

        lstsh = Tovost.objects.all()


    return render(request, 'sshdapp/ftbl.html', context={'lstsh' : lstsh})

def instrp_view(request):

    f_uin = request.POST.get("f_uin", "")
    print('*')
    print(f_uin)


    return render(request, 'sshdapp/instrp.html', context={})



#def spr_sez_view(request):
#
#    if request.method == 'GET':
#        form = SezonForm()
#        return render(request, 'sshdapp/spr_sez.html', context={'form': form})
#    else:
#        form = SezonForm(request.POST, files=request.FILES)
#        if form.is_valid():
#            form.save()
#            return HttpResponseRedirect(reverse('blog:index'))
#        else:
#            return render(request, 'blogapp/create.html', context={'form': form})

# CRUD CREATE, READ (LIST, DETAIL), UPDATE, DELETE

class NameContextMixin(ContextMixin):

    def get_context_data(self, *args, **kwargs):
        """
        Отвечает за передачу параметров в контекст
        :param args:
        :param kwargs:
        :return:
        """
        context = super().get_context_data(*args, **kwargs)
        context['name'] = 'Теги'

        #print(context)

        return context

class SezListView(ListView, NameContextMixin):
    model = Sezon
    template_name = 'sshdapp/spr_sez.html'
    context_object_name = 'name'

    def get_queryset(self):
        """
        Получение данных
        :return:
        """
        print('***')
        zn = Sezon.objects.all()
        print(len(zn))

        return zn

class RazmListView(ListView, NameContextMixin):
    model = Razm
    template_name = 'sshdapp/spr_razm.html'
    context_object_name = 'name'

    def get_queryset(self):
        """
        Получение данных
        :return:
        """
        print('***')
        zn = Razm.objects.all()
        print(len(zn))

        return zn

class TovostListView(ListView, NameContextMixin):
    model = Tovost
    template_name = 'sshdapp/ftbl.html'
    context_object_name = 'name'

    def get_queryset(self):

        prm = self.kwargs.get('sez')
        print(type(prm))
        print(prm)
        ls = prm.split('&')
        print(ls)

        prmsez = ls[0]
        if len(ls) == 1:
            prmrazm = ' '
        else:
            prmrazm = ls[1]
            prmrazm = prmrazm.replace(' ','/')

        c_sez = Sezon.objects.filter(name=prmsez).first()

        #prmrazm = ' ' #self.kwargs.get('razm')
        print(type(prmrazm))
        print(prmrazm)
        c_razm = Razm.objects.filter(name=prmrazm).first()

        if prmsez == ' ':
            zn = Tovost.objects.all()
        else:
            if prmrazm == ' ':
                zn = Tovost.objects.filter(sezonnost=c_sez).all()
            else:
                zn = Tovost.objects.filter(razmer=c_razm, sezonnost=c_sez).all()

        return zn

class TovostDetail(DetailView, NameContextMixin):
    model = Tovost
    template_name = 'sshdapp/instrp.html'

    def get(self, request, *args, **kwargs):

        self.uin = kwargs['uin']
        return super().get(request, *args, **kwargs)
    def get_object(self, queryset=None):

        return get_object_or_404(Tovost, uin=self.uin)

siteshd/sshdapp/templates/sshdapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Business Frontpage - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-5">
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-6">
                        <div class="text-center my-5">
                            <h1 class="display-5 fw-bolder text-white mb-2">Магазин <br>автомобильных шин</h1>
                            <p class="lead text-white-50 mb-4">Просмотр товарных позиций по размеру и сезонности</p>
                        </div>
                    </div>
                </div>
            </div>
        </header>


        <content>{% block content %} {% endblock %} </content>


        <!-- Footer-->
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

siteshd/sshdapp/templates/sshdapp/ftbl.html
<html>
<head>Список шин</head>
    <body>
    <title>Список шин</title>

<!--table - таблица, tr-строка, td-столбец, th-заголовок-->

                    <table> <table cellspacing=5><table border=5>

                        <tr>
                            <th> № п/п </th>
                            <th> Название </th>
                            <th> Цена </th>
                            <th> Сезонность </th>
                            <th> Шипы </th>
                            <th> УИН </th>
                        </tr>

                        {% for item in object_list %}

                        <tr>
                            <td>{{ forloop.counter }} </td>
                            <td>{{ item.name }}</td>
                            <td>{{ item.cena }}</td>
                            <td>{{ item.sezonnost }}</td>
                            <td>{{ item.ship }}</td>
                            <td>{{ item.uin }}</td>

                            <td><a href="{% url 'sshdapp:instrp' uin=item.uin %}">Просмотреть</a></td>

                        </tr>

                        {% endfor %}

                        </table>





        <a href="{% url 'sshdapp:index' %}">На главную</a>

    </body>
</html>

siteshd/sshdapp/templates/sshdapp/index.html
{% extends "base.html" %}

{% block content %}

        <!-- Features section-->
        <section class="py-5 border-bottom" id="features">
            <div class="container px-5 my-5">
                <div class="row gx-5">
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-collection"></i></div>
                        <h2 class="h4 fw-bolder">Ввод данных для поиска</h2>
                        <p>Для того чтобы поиск заработал ему нужно указать данные.</p>
                        <a class="text-decoration-none" href="#!">
                            <a href="{% url 'sshdapp:vvod' %}">Ввести</a>
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-building"></i></div>
                        <h2 class="h4 fw-bolder">Просмотр всех товарных позиций</h2>
                        <p>Здесь можно просмотреть данные по всем шинам.</p>
                        <a class="text-decoration-none" href="#!">
                            <a href="{% url 'sshdapp:ftbl' sez=' ' %}">Все</a>
                            <i class="bi bi-arrow-right"></i>
                        </a>
                        <br>
                        <a class="text-decoration-none" href="#!">
                            <a href="{% url 'sshdapp:ftbl' sez='Летняя'  %}">Летние</a>
                            <i class="bi bi-arrow-right"></i>
                        </a>
                        <br>
                        <a class="text-decoration-none" href="#!">
                            <a href="{% url 'sshdapp:ftbl' sez='Зимняя' %}">Зимние</a>
                            <i class="bi bi-arrow-right"></i>
                        </a>

                    </div>


                    <div class="col-lg-4">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-toggles2"></i></div>
                        <h2 class="h4 fw-bolder">Справочники</h2>
                        <p></p>
                        <a class="text-decoration-none" href="#!">
                            <a href="{% url 'sshdapp:spr_sez' %}">Сезонность</a>
                            <i class="bi bi-arrow-right"></i>
                        </a>
                        <br>
                        <a class="text-decoration-none" href="#!">
                            <a href="{% url 'sshdapp:spr_razm' %}">Размеры</a>
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>



                </div>
            </div>
        </section>

{% endblock %}

siteshd/sshdapp/templates/sshdapp/instrp.html
<html>
<head>Данные о шине</head>
    <body>
    <title>Карточка товара</title>


    <!--
        <dl>
            <dt>{{ uin }}</dt>
            <dd>Наименование : {{ object.name }}</dd>
            <dd>Шипы : {{ object.ship }}</dd>
            <dd>Цена : {{ object.cena }}</dd>
            <dd>Остаток : {{ object.ostatok }}</dd>
        </dl>

        -->

        <table> <table cellspacing=5><table border=5>
        <tr>
            <td>Наименование</td>
            <td>{{ object.name  }}</td>
        </tr>
        <tr>
            <td>Размер</td>
            <td>{{ object.razmer  }}</td>
        </tr>
        <tr>
            <td>Сезонность</td>
            <td>{{ object.sezonnost }}</td>
        </tr>
        <tr>
            <td>Шипы</td>
            <td>{{ object.ship }}</td>
        </tr>
        <tr>
            <td>УИН</td>
            <td>{{ object.uin }}</td>
        </tr>
        <tr>
            <td>Цена</td>
            <td>{{ object.cena }}</td>
        </tr>
        <tr>
            <td>Остаток</td>
            <td>{{ object.ostatok }}</td>
        </tr>
        <tr>
            <td>Описание</td>
            <td>{{ object.descriptions }}</td>
        </tr>
        <tr>
            <td>Адрес картинки</td>
            <td>{{ object.kartss }}</td>
        </tr>
        <tr>
            <td>Картинка</td>
            <td>

            <img src="{{ object.kartss }}" alt="Картинка" width="300">



            </td>

        </tr>


        </table>

        <a href="{% url 'sshdapp:index' %}">На главную</a>

    </body>
</html>

siteshd/sshdapp/templates/sshdapp/spr_razm.html
<html>
<head>Справочник "Размеры"</head>
    <body>


    <title>Справочник "Размеры"</title>
        <table> <table cellspacing=5><table border=5>
            <thead class="thead-dark">
                <tr>
                    <th scope="col">№ п/п</th>>
                    <th scope="col">Наименование</th>>
                </tr>
            </thead>
            <tbody>
                {% for item in object_list %}
                    <tr>
                        <td> {{ forloop.counter }} </td>
                        <td> {{ item.name }} </td>
                    </tr>
               {% endfor %}
            </tbody>>
        </table>>
        <a href="{% url 'sshdapp:index' %}">На главную</a>


    </body>
</html>

siteshd/sshdapp/templates/sshdapp/spr_sez.html
<html>
<head>Справочник "Сезонность"</head>
    <body>

    <title>>Справочник "Cезонность"</title>
        <<table> <table cellspacing=5><table border=5>
                <tr>
                    <th scope="col">№ п/п</th>>
                    <th scope="col">Наименование</th>>
                </tr>
            </thead>
            <tbody>
                {% for item in object_list %}
                    <tr>
                        <td> {{ forloop.counter }} </td>
                        <td> {{ item.name }} </td>
                    </tr>
               {% endfor %}
            </tbody>>
        </table>>
        <a href="{% url 'sshdapp:index' %}">На главную</a>


    </body>
</html>

siteshd/sshdapp/templates/sshdapp/vvod.html
{% extends "base.html" %}

{% block content %}

        <!-- Features section-->
        <section class="py-5 border-bottom" id="features">
            <div class="container px-5 my-5">
                <div class="row gx-5">
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-collection"></i></div>
                        <h2 class="h4 fw-bolder">Ввод исходных данных</h2>
                        <a class="text-decoration-none" href="#!">
                            <a href="/">На главную.</a>
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>
                    <div class="col-lg-4 mb-5 mb-lg-0">

                    <h2>Укажите данные для подбора</h2>
<!--                    <form method="get" action="{% url 'sshdapp:ftbl' sez='Летняя&15 195 65' %}">
-->
                    <form method="get" action="{% url 'sshdapp:ftbl' sez=' ' %}">
                        {% csrf_token %}
                        <p>Сезонность:<br> <input name='f_sez' /></p>
                        <p>Размер:<br> <input name='f_razm' /></p>
                        <input type="submit" value="Найти" />
                    </form>

                </div>
            </div>
        </section>

{% endblock %}